### ISSUE TITLE
Errors don't give full path to config value

### ISSUE THREAD

**Issue by vix597** [ameily/cincoconfig#22]
For example, a nested `SecureField`: `config.one.two.three.password = SecureField()` will raise a `ValueError` if set to something invalid and that error will be something like: `Error: password invalid` when it should be `Error: one.two.three.password invalid`

**Comment by vix597** [comment]
Looking at this issue, it's actually a bigger fix than I initially realized. We're using `self.name` everywhere to report errors and we should be using `self.key` (I think - if not than what we need doesn't exist). We need some way to get the full path (root to field) from the field itself. But we don't track the parent in a field so I'm not 100% sure how to do it.

**Comment by vix597** [comment]
In additon to this, for `Fields` like `FilenameField` we should be including the value in the error message. So if a file doesn't, the error message should contain: Full path to file that doesn't exist and full path from root to field for the actual field that caused the error.

**Comment by ameily** [comment]
I resolved this by wrapping any exception raised in the field validation in a new `ValidationError` exception, which will contain the full path to the field in the message.

`Field.name` is meant to be a friendly name of the field. For example:

```python
schema.db.ssl_ca_certfile = FilenameField(name='Database SSL CA Certificates File')
```

`Field.friendly_name()` will return `Field.name` if it is different than `Field.key` otherwise it'll return `Field.full_path()` (x.y.z)
